#ifndef _GAME_CONST_H
#define _GAME_CONST_H

#define TAG_BIRD 1
#define BIRD_CATEGORY_BITMASK					0x01
#define BIRD_COLLISION_AND_CONTACT_TEST_BITMASK 0x02
#define PIPE_CATEGORY_BITMASK					0x02
#define PIPE_COLLISION_AND_CONTACT_TEST_BITMASK 0x01
#endif // !_GAME_CONST_H
